(function(){
var d=null,f=(new Date).getTime();function k(a,b){try{return a.top.document.URL==b.URL}catch(c){}return false}function l(a,b,c,e){var g=c||a.google_ad_width,n=e||a.google_ad_height;if(k(a,b))return false;var h=b.documentElement;if(g&&n){var i=1,j=1;if(a.innerHeight){i=a.innerWidth;j=a.innerHeight}else if(h&&h.clientHeight){i=h.clientWidth;j=h.clientHeight}else if(b.body){i=b.body.clientWidth;j=b.body.clientHeight}if(j>2*n||i>2*g)return false}return true}function m(a,b){if(!b)return a.URL;return a.referrer}
function o(a,b){if(!b&&a.google_referrer_url==d)return"0";else if(b&&a.google_referrer_url==d)return"1";else if(!b&&a.google_referrer_url!=d)return"2";else if(b&&a.google_referrer_url!=d)return"3";return"4"}function p(a,b,c,e){a.page_url=m(c,e);a.page_location=d}function q(a,b,c,e){a.page_url=b.google_page_url;a.page_location=m(c,e)||"EMPTY"}
function r(a,b){var c={},e=l(a,b,a.google_ad_width,a.google_ad_height);c.iframing=o(a,e);a.google_page_url?q(c,a,b,e):p(c,a,b,e);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1000:d;c.referrer_url=e?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function s(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=d;b.page_url=c;b.page_location=a.URL;b.last_modified_time=d;b.referrer_url=c;return b}
function t(a,b){var c;return c=a.google_page_url==d&&u[b.domain]?s(b):r(a,b)}var u={};u["ad.yieldmanager.com"]=true;var v={google_ad_channel:"channel",google_ad_format:"format",google_ad_height:"h",google_ad_width:"w",google_box_len:"box_len",google_button_pos:"btn_pos",google_color_bg:"color_bg",google_color_link:"color_link",google_color_text:"color_text",google_correlator:"correlator",google_encoding:"oe",google_link_target:"same_win",google_logo_pos:"logo",google_rs_pos:"rl_pos",google_ss_domains:"ss_dmns",google_adtest:"adtest",google_button_color_bg:"btn_bg",google_cts_font_size:"cts_size",google_cts_mode:"cts_mode",
google_num_cts:"num_cts",google_searchbox_color_border:"box_bdr",google_searchbox_height:"box_h",google_searchbox_width:"box_w"};function w(a){if(a.google_ad_frameborder==d)a.google_ad_frameborder=0;if(a.google_correlator==d)a.google_correlator=f}function x(a,b){if(a&&(b||b===0||b===false))return"&"+encodeURIComponent(a)+"="+encodeURIComponent(b);return""}function y(a){return a||a===0||a===false?'"'+a+'"':'""'}
function z(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function A(a){var b="";if(a.screen){b+=x("u_h",a.screen.height);b+=x("u_w",a.screen.width);b+=x("u_ah",a.screen.availHeight);b+=x("u_aw",a.screen.availWidth);b+=x("u_cd",a.screen.colorDepth)}var c=-(new Date).getTimezoneOffset();b+=x("u_tz",c);if(a.history)b+=x("u_his",a.history.length);if(a.navigator){b+=x("u_java",a.navigator.javaEnabled());if(a.navigator.plugins)b+=x("u_nplug",a.navigator.plugins.length);if(a.navigator.mimeTypes)b+=x("u_nmime",a.navigator.mimeTypes.length)}return b}
function B(a){var b=(new Date).getTime()-f,c="&dtd="+(b<1000?b:"M");return a+c}
function C(a,b){if(a.google_num_sdo_slots)if(a.google_num_sdo_slots>=4)return"";else++a.google_num_sdo_slots;else a.google_num_sdo_slots=1;var c="http://googleads.g.doubleclick.net/pagead/sdo?";c+="client="+encodeURIComponent(z(a.google_ad_client));c+=x("output","html");c+=x("dt",f);for(var e in v)c+=x(v[e],a[e]);c+=A(a);var g=t(a,b);c+=x("frm",g.iframing);c+=x("lmt",g.last_modified_time);c+=x("url",g.page_url);c+=x("loc",g.page_location);c+=x("ref",g.referrer_url);return c}
function D(a){for(var b in v)b=="google_correlator"||(a[b]=d)}function E(){var a=window,b=document;w(a);var c=C(a,b);c&&F(a,b,c);D(a)}function F(a,b,c){var e='<iframe name="google_sdo_frame" width='+y(a.google_ad_width)+" height="+y(a.google_ad_height)+" frameborder="+y(a.google_ad_frameborder)+" src="+y(B(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';b.write(e)};E();
})()
